from __future__ import annotations

SCHEMA_VERSION = 1
EXPORTER_VERSION = "0.1.0"

HISTORY_COLUMNS = [
    "transcriptEntityId",
    "asrText",
    "formattedText",
    "editedText",
    "timestamp",
    "audio",
    "screenshot",
    "additionalContext",
    "status",
    "app",
    "url",
    "e2eLatency",
    "needsUploading",
    "duration",
    "numWords",
    "shareType",
    "textboxContents",
    "appVersion",
    "editedTextStatus",
    "editedTextAttempts",
    "toneMatchedText",
    "toneMatchPairs",
    "feedback",
    "language",
    "isArchived",
    "micDevice",
    "conversationId",
    "formattingDivergenceScore",
    "pastedText",
    "defaultAsrText",
    "fallbackAsrText",
    "defaultFormattedText",
    "fallbackFormattedText",
    "fallbackAsrDivergenceScore",
    "fallbackFormattingDivergenceScore",
    "detectedLanguage",
    "averageLogProb",
    "hasRevertedAI",
    "userEditMetaData",
    "usedFallbackAsr",
    "usedFallbackFormatting",
    "calledExternalAsr",
    "transcriptOrigin",
    "platform",
    "transcriptCommand",
    "personalizationStyleSettings",
    "clientNetworkLatency",
    "fallbackLevel",
    "speechDuration",
    "timezoneOffsetMinutes",
    "numWordsCorrected",
    "numDictionaryReplacements",
]

DICTIONARY_COLUMNS = [
    "id",
    "phrase",
    "replacement",
    "teamDictionaryId",
    "lastUsed",
    "frequencyUsed",
    "remoteFrequencyUsed",
    "manualEntry",
    "createdAt",
    "modifiedAt",
    "isDeleted",
    "source",
    "isSnippet",
    "observedSource",
    "isStarred",
]
